name: pipeline-scan 

on: push

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print current path
        run: echo "Current path is $GITHUB_WORKSPACE"
      - name: List contents of the target path
        run: ls -al $GITHUB_WORKSPACE
      - name: Create zip archive
        run: zip -r veracode.zip . -x .git/**\* bin/**\* e2e/**\* tests/**\* node_modules/**\* *.pyd *.mwb *.exe *.dll *.bin *.png *.xml *.bat *.g2p *.gp4 *.wav *.jpg *.svg *.sfx *.prx *.sb *.nrm *.config *.ini *.pdf *.dat *.docx *.whl *.so *_arm64 *_armhf *_x64 *.xlsm *.sql
      - name: List contents of the target path
        run: ls -al $GITHUB_WORKSPACE  
      - uses: actions/upload-artifact@v4
        with:
          name: veracode
          path: veracode.zip
  pipeline-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      # get the package from a previous job
      - name: get archive
        uses: actions/download-artifact@v4
        with:
          name: veracode
          path: .
      - name: Display structure of downloaded files
        run: ls -R
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Veracode CLI
        uses: wei/curl@master
        with:
          args: -fsS https://tools.veracode.com/veracode-cli/install | sh
      - name: Run a static scan
        run: ./veracode static scan veracode.zip  --fail-on-severity="Very High, High"
        env:
          VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}

  upload-and-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      # get the compiled binary from a previous job
      - name: get archive
        uses: actions/download-artifact@v4
        with:
          name: veracode
          path: .
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'Verademo Javascript API'
          createprofile: false
          filepath: 'veracode.zip'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'

  Veracode-container_iac_secrets-scan:
    runs-on: ubuntu-latest
    name: Veracode Container/IaC/Secrets scan

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Veracode Container/IaC/Secrets action step
        uses: veracode/container_iac_secrets_scanning@v1.0.1
        with:
          vid: ${{  secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          command: "scan" 
          type: "directory"
          source: "./"
          format: "json"
          debug: false
          fail_build: false
