name: pipeline-scan 

on: push

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Print current path
        run: echo "Current path is $GITHUB_WORKSPACE"
      - name: List contents of the target path
        run: ls -al $GITHUB_WORKSPACE/target
      - uses: actions/upload-artifact@v4
        with:
          name: verademoJS
          path: ./**/*
  pipeline-scan:
    runs-on: veracode/pipeline-scan:latest
    needs: build
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      # get the package from a previous job
      - name: get archive
        uses: actions/download-artifact@v4
        with:
          name: verademoJS
          path: .
      - name: Display structure of downloaded files
        run: ls -R
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Pipeline Scanner
        run: java -Dpipeline.debug=true -jar /opt/veracode/pipeline-scan.jar --veracode_api_id "${{secrets.VERACODE_API_ID}}" --veracode_api_key "${{secrets.VERACODE_API_KEY}}" --file "verademo.war" --fail_on_severity="Very High, High"
        
